apiVersion : apps/v1
kind: Deployment
metadata:
  name: "javaspringboot-fa4a"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "javaspringboot-fa4a"
  template:
    metadata:
      labels:
        app: "javaspringboot-fa4a"
    spec:
      containers:
        - name: "javaspringboot-fa4a"
          image: "idsvnacr.azurecr.io/javaspringboot"
          ports:
          - containerPort: 8080
