on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: idsvnasiaacr.azurecr.io
        username: ${{ secrets.acr_idsvnasiaacr_username }}
        password: ${{ secrets.acr_idsvnasiaacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/complete" -f  "complete/Dockerfile" -t idsvnasiaacr.azurecr.io/javaspringboot:${{ github.sha }} --label dockerfile-path=complete/Dockerfile
        docker push idsvnasiaacr.azurecr.io/javaspringboot:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_javaspringboot_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep java-spring-boot8047 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace java-spring-boot8047`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: java-spring-boot8047
        container-registry-url: idsvnasiaacr.azurecr.io
        container-registry-username: ${{ secrets.acr_idsvnasiaacr_username }}
        container-registry-password: ${{ secrets.acr_idsvnasiaacr_password }}
        secret-name: javaspringbodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: java-spring-boot8047
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          idsvnasiaacr.azurecr.io/javaspringboot:${{ github.sha }}
        imagepullsecrets: |
          javaspringbodockerauth
